### ISSUE TITLE
请增加请你喝咖啡的二维码

### ISSUE THREAD

**Issue by Cdners** [Cloxl/xhshow#12]
帮了我大忙, 非常感谢~

**Comment by Cloxl** [comment]
哈哈 我之前更新了readme 忘记推送了
最近更新的这个发现github不能显示圆形

**Comment by Cloxl** [comment]
最新readme已经有赞赏了
感谢你的支持

**Comment by Cdners** [comment]
> 最新readme已经有赞赏了 感谢你的支持

已赞赏~

**Comment by Cloxl** [comment]
> > 最新readme已经有赞赏了 感谢你的支持
> 
> 已赞赏~

感谢支持 可以关注一下后续项目更新 等我解决完验证码问题 会推送纯协议登录 纯算纯协议过旋转验证码

**Comment by Cdners** [comment]
> > > 最新readme已经有赞赏了 感谢你的支持
> > 
> > 
> > 已赞赏~
> 
> 感谢支持 可以关注一下后续项目更新 等我解决完验证码问题 会推送纯协议登录 纯算纯协议过旋转验证码

wc, 纯算纯协议过旋转验证码, 期待~   感谢大佬~

**Comment by Cloxl** [comment]
> > > > 最新readme已经有赞赏了 感谢你的支持
> > > 
> > > 
> > > 已赞赏~
> > 
> > 感谢支持 可以关注一下后续项目更新 等我解决完验证码问题 会推送纯协议登录 纯算纯协议过旋转验证码
> 
> wc, 纯算纯协议过旋转验证码, 期待~   感谢大佬~ 

已支持验证码轨迹生成 晚点会推送纯算xsc
目前还差b1生成就能纯算纯协议过旋转验证码

**Comment by Cdners** [comment]
> > > > > 最新readme已经有赞赏了 感谢你的支持
> > > > 
> > > > 
> > > > 已赞赏~
> > > 
> > > 
> > > 感谢支持 可以关注一下后续项目更新 等我解决完验证码问题 会推送纯协议登录 纯算纯协议过旋转验证码
> > 
> > 
> > wc, 纯算纯协议过旋转验证码, 期待~   感谢大佬~
> 
> 已支持验证码轨迹生成 晚点会推送纯算xsc 目前还差b1生成就能纯算纯协议过旋转验证码

膜拜大佬~ 期待~
