### ISSUE TITLE
这个验证码的图是怎么弄得

### ISSUE THREAD

**Issue by 359369407** [Cloxl/xhshow#14]

**Comment by Cloxl** [comment]
基于url去重 手动旋转到正确的角度 再使用mse得出最像的角度 就是正确的旋转角度

**Comment by 359369407** [comment]
那个sign生成MD5的地方没有url=这个吧

**Comment by Cloxl** [comment]
> 那个sign生成MD5的地方没有url=这个吧

对的 在我的项目中 只需要传递uri+payload 我已经做了自动加url=处理

**Comment by 359369407** [comment]
我的意思是 不需要加url= 不然出的x-s不对
