### ISSUE TITLE
验证码图像覆盖率问题

### ISSUE THREAD

**Issue by txuw** [Cloxl/xhshow#15]
目前给出的验证码图像涉及到的bg_nums好像还是不够多，这边retry了5-6次都返回None值

- 这边现在要做到拓展验证码池，是需要拿到对应的bk和center手动转好放到static，然后进行bg_nums的映射，这样来扩充池子吗？
- 有没有更好的方法，比如比较高效的扩充bg_nums，比如非人工的方式去旋转这个bk和center映射
- 平常作者正常使用的话，需要retry几次能命中对应的bg_nums呢，这5-6次好像不太够用

【昨天请作者喝了杯咖啡，没找到联系方式哈哈】

**Comment by PrintX05** [comment]
+1 我这边解决方案是直接用的cv  获取背景和旋转图然后自己cv计算角度距离和轨迹

**Comment by 359369407** [comment]
为啥这玩意手滑都过不了

**Comment by Cloxl** [comment]
> 目前给出的验证码图像涉及到的bg_nums好像还是不够多，这边retry了5-6次都返回None值
> 
> * 这边现在要做到拓展验证码池，是需要拿到对应的bk和center手动转好放到static，然后进行bg_nums的映射，这样来扩充池子吗？
> * 有没有更好的方法，比如比较高效的扩充bg_nums，比如非人工的方式去旋转这个bk和center映射
> * 平常作者正常使用的话，需要retry几次能命中对应的bg_nums呢，这5-6次好像不太够用
> 
> 【昨天请作者喝了杯咖啡，没找到联系方式哈哈】

项目使用的是根据答案做题目的方式完成的
当题目更新时 只能更新答案库
最近xhs确实拓展了图片 工作我没有及时更新

xhs在请求验证码注册接口时调用 XsEncrypt.encrypt_sign传参url
url组成为: `xt+"test"+uri+payload `
其中  payload按照以下代码生成
```
json.dumps(payload, separators=(',', ':'), ensure_ascii=False))
```
示例url: 
```
1731976328439test/api/redcaptcha/v2/captcha/register{"secretId":"000","verifyType":"102","verifyUuid":"","verifyBiz":"461","sourceSite":"","captchaVersion":"1.3.0"}
```
原理如下:  
![Clip_2024-11-19_08-36-37](https://github.com/user-attachments/assets/9999f0c9-341e-40ab-af66-9d5037e26209)
![Clip_2024-11-19_08-35-30](https://github.com/user-attachments/assets/67429434-928e-4d46-816d-e153629ac699)

当答案更新时 应该调用XsEncrypt.encrypt_sign去获取几千个值 通过背景url去重 得到所有的验证码子图 再手动旋转到正确位置
如果不想这么麻烦 可以使用cnn训练一个模型 考虑到便携性 我采用了mse匹配正确答案
[cnn训练项目](https://github.com/8yteDance/RotateCaptcha)

感谢你的赞助 当时我确实想帮助你解决问题 可惜我看见的信息太少了
![Clip_2024-11-19_08-45-05](https://github.com/user-attachments/assets/54f0cc92-db4c-4b2f-8e5b-ecd05ff5272f)
根据txuw 我搜索了微信 bilibili都没找到账户 bilibili确实有你的账户 但是有三个相同的账户使用txuw作为用户名 我不太确定 就放弃寻找了

**Comment by Cloxl** [comment]
> 为啥这玩意手滑都过不了

验证 验证码的接口会验证xsc 需要调用xsc纯算生成才行
轨迹无需担心 不是太抽象的轨迹都能过

xsc纯算目前我的主要研究方向是纯算生成b1参数
暂时可以开一个浏览器获取生成的 b1解决

**Comment by Cloxl** [comment]
> +1 我这边解决方案是直接用的cv 获取背景和旋转图然后自己cv计算角度距离和轨迹

这也是一种解决办法 哈哈

**Comment by Cloxl** [comment]
> 非常感谢回复，等我周末有空闲时间时钻研一下 目前参考作者的代码，结合之前我个人对xs的研究，现在验证码信息都能拿到 只是在发送验证码check请求的时候，一直都是 fail pass ，有点抽象，还特地确认了target_x的角度和正确角度是一致的，可能是我个人项目中计算的某个xs参数或者轨迹算法没对上，哈哈

check接口验证x-s-common 可以使用我项目的纯算xsc 但是b1参数我目前还无法纯算生成 可以开一个浏览器rpc获取b1参数

**Comment by Cloxl** [comment]
标准答案已更新

**Comment by souldjl** [comment]
> 标准答案已更新

没看懂怎么解决的呀，大佬们，有看懂的嘛

**Comment by txuw** [comment]
> > 标准答案已更新
> 
> 没看懂怎么解决的呀，大佬们，有看懂的嘛

小红书旋转码这块已经不当人了，兄弟放弃吧

**Comment by ken73666** [comment]
你们什么频率会出现旋转码？

**Comment by souldjl** [comment]
> > > 标准答案已更新
> > 
> > 
> > 没看懂怎么解决的呀，大佬们，有看懂的嘛
> 
> 小红书旋转码这块已经不当人了，兄弟放弃吧
 好的，我已经放弃了

**Comment by PingWorkStudio** [comment]
大佬们，这是在讨论啥的，咋都看不懂啊
