### ISSUE TITLE
貌似更新56了

### ISSUE THREAD

**Issue by PrintX05** [Cloxl/xhshow#17]
.

**Comment by Cloxl** [comment]
上午才看到信息 花了5分钟逆向后就破解了 哈哈

**Comment by PrintX05** [comment]
> 上午才看到信息 花了5分钟逆向后就破解了 哈哈

就是我email的 嘿嘿嘿

**Comment by Cloxl** [comment]
你可以按照encrypt下的编程范式写一个b1生成方法 放于misc_encrypt 再发起一个pr

**Comment by Cloxl** [comment]
没有仔细测 算法一般是不会更新的 即使是小红书验证最多的xs  也只是更新key 和 iv
只需要额外维护这俩个值即可
![Clip_2024-12-02_15-40-04](https://github.com/user-attachments/assets/3ca4b931-e4b7-4212-908a-6a9734ddc9d5)

**Comment by PrintX05** [comment]
等回家我鼓捣鼓捣



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Cloxl/xhshow] 貌似更新56了 (Issue #17)




 
没有仔细测 算法一般是不会更新的 即使是小红书验证最多的xs  也只是更新key 和 iv
 只需要额外维护这俩个值即可
 Clip_2024-12-02_15-40-04.png (view on web)
